import { z } from "zod";
import { contractRegistry } from "./registry.js";
import { CONTRACT_MAJOR_PATH, CONTRACT_MINOR } from "./version.js";

/**
 * Build the JSON-Schema artefact consumed by the Swift agent (R9).
 *
 * ⚠️ `io: "input"` is load-bearing, not a style choice. The default emits
 * `additionalProperties: false`, which would tell a generated Swift decoder to
 * REJECT unknown fields — the exact failure R1 exists to prevent, and
 * invisible from the TypeScript side because the zod schemas themselves stay
 * tolerant. `emit.test.ts` fails the build if any strict object reappears.
 */
export function buildArtefact(): Record<string, unknown> {
  const { schemas } = z.toJSONSchema(contractRegistry, { io: "input" }) as {
    schemas: Record<string, unknown>;
  };
  return {
    $comment:
      "GENERATED by packages/contract/src/emit.ts — do not edit. Run `pnpm --filter @hpc/contract emit`.",
    contract: { major: CONTRACT_MAJOR_PATH, minor: CONTRACT_MINOR },
    schemas,
  };
}

/** Every path in an emitted schema that forbids unknown fields. Must always be empty (R1). */
export function strictPaths(node: unknown, path = "$"): string[] {
  if (!node || typeof node !== "object") return [];
  const found: string[] = [];
  const obj = node as Record<string, unknown>;
  if (obj.additionalProperties === false) found.push(path);
  for (const [k, v] of Object.entries(obj)) found.push(...strictPaths(v, `${path}.${k}`));
  return found;
}
